version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-docker-secret-key
      - ALLOWED_HOSTS=localhost,127.0.0.1,web
      - DATABASE_URL=postgresql://postgres:password@db:5432/shared_finance
    depends_on:
      - db
      - redis
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shared_finance
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build: .
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-docker-secret-key
      - ALLOWED_HOSTS=localhost,127.0.0.1,web
      - DATABASE_URL=postgresql://postgres:password@db:5432/shared_finance
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data:
  redis_data:
  media_volume: