# Generated by Django 4.2 on 2025-09-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('payment_initiated', 'Payment Initiated'), ('payment_completed', 'Payment Completed'), ('settlement_computed', 'Settlement Computed')], max_length=30)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'audits_auditlog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('expense_analysis', 'Expense Analysis'), ('settlement_calculation', 'Settlement Calculation'), ('group_insights', 'Group Insights'), ('payment_processing', 'Payment Processing')], max_length=30)),
                ('audience', models.CharField(choices=[('group_members', 'Group Members'), ('group_owner', 'Group Owner'), ('system', 'System'), ('third_party', 'Third Party')], max_length=20)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('consent_token', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audits_consent',
                'ordering': ['-created_at'],
            },
        ),
    ]
