# Generated by Django 4.2 on 2025-09-06 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FairnessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('equal_split', 'Equal Split'), ('income_based', 'Income Based'), ('custom_share', 'Custom Share'), ('proportional', 'Proportional to Expenses')], max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'groups_fairnesspolicy',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('group_type', models.CharField(choices=[('roommates', 'Roommates'), ('society', 'Society Committee'), ('club', 'Club/Organization'), ('family', 'Family'), ('friends', 'Friends'), ('business', 'Business'), ('other', 'Other')], default='other', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('gst_mode', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'groups_group',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('treasurer', 'Treasurer'), ('auditor', 'Auditor'), ('member', 'Member')], default='member', max_length=20)),
                ('share_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('income_bracket', models.CharField(choices=[('low', 'Low Income'), ('medium', 'Medium Income'), ('high', 'High Income')], default='medium', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group')),
            ],
            options={
                'db_table': 'groups_groupmember',
            },
        ),
    ]
