# Generated by Django 4.2 on 2025-09-06 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('invoice_no', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('utilities', 'Utilities'), ('rent', 'Rent & Accommodation'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('travel', 'Travel'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('ocr_data', models.JSONField(blank=True, default=dict)),
                ('is_settled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'expenses_expense',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_owed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('split_type', models.CharField(choices=[('equal', 'Equal Split'), ('percentage', 'Percentage'), ('amount', 'Fixed Amount'), ('share_factor', 'Share Factor')], default='equal', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='expenses.expense')),
            ],
            options={
                'db_table': 'expenses_expensesplit',
            },
        ),
    ]
